# Generated by Django 4.2.7 on 2024-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_publisher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
