# Generated by Django 4.2.7 on 2024-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_address',
            field=models.TextField(),
        ),
    ]
